# Generated by Django 2.0.7 on 2018-07-13 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
                ('posted_by', models.CharField(max_length=40)),
                ('date_posted', models.DateTimeField(default=datetime.datetime.now)),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AlterModelOptions(
            name='login',
            options={'verbose_name_plural': 'Login'},
        ),
    ]
